[phases.setup]
nixPkgs = ["php80", "php80Extensions.mongodb", "php80Extensions.redis", "php80Extensions.pdo_mysql", "php80Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --ignore-platform-reqs"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."